import type { StickerConfig } from "@/components/dashboard/StickerDesigner";

export interface BatchPrintTemplate {
  id: string;
  name: string;
  description: string;
  /** Уникальный шаблон А4-листа: красивое размещение 8×8 см стикеров + инструкция. */
  sheetLayout?: "premium-a4-8x8";
  config: Omit<StickerConfig, "url" | "pdfCount">;
}

export const BATCH_PRINT_TEMPLATES: BatchPrintTemplate[] = [
  {
    id: "premium-a4-8x8",
    name: "Премиум A4 · 8×8 см",
    description: "Красивый лист A4: 4 стикера 8×8 см с линиями реза, инструкцией и брендингом",
    sheetLayout: "premium-a4-8x8",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру на QR",
      labels: ["★★★★★"],
      formatId: "8x8",
      layoutId: "standard",
      paletteId: "light",
      brandColor: "#4F46E5",
      dotStyle: "rounded",
      eyeStyle: "rounded",
      showWatermark: false,
    },
  },
  {
    id: "review-dark-a6",
    name: "Отзывы — тёмный",
    description: "A6 лежачий (тейбл-тент), тёмный фон, для ресторанов и кафе",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру на QR",
      labels: ["ОТЗЫВ", "5 СЕКУНД"],
      formatId: "a6l",
      layoutId: "standard",
      paletteId: "dark",
      brandColor: "#4F46E5",
      dotStyle: "rounded",
      eyeStyle: "rounded",
      showWatermark: false,
    },
  },
  {
    id: "review-light-a6",
    name: "Отзывы — светлый",
    description: "A6 лежачий (тейбл-тент), белый фон, минимализм",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру на QR",
      labels: ["ОТЗЫВ", "БЫСТРО"],
      formatId: "a6l",
      layoutId: "standard",
      paletteId: "light",
      brandColor: "#4F46E5",
      dotStyle: "rounded",
      eyeStyle: "square",
      showWatermark: false,
    },
  },
  {
    id: "review-dark-7x7",
    name: "Стикер 7×7 — тёмный",
    description: "Квадратный стикер 7×7 см, тёмный, стандартный макет",
    config: {
      headline: "ОТЗЫВ",
      ctaText: "Наведите камеру",
      labels: [],
      formatId: "7x7",
      layoutId: "standard",
      paletteId: "dark",
      brandColor: "#4F46E5",
      dotStyle: "dots",
      eyeStyle: "rounded",
      showWatermark: false,
    },
  },
  {
    id: "review-sunset-7x7",
    name: "Стикер 7×7 — Sunset",
    description: "Квадратный стикер 7×7 см, тёплый градиент, стандартный макет",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру",
      labels: ["★★★★★"],
      formatId: "7x7",
      layoutId: "standard",
      paletteId: "sunset",
      brandColor: "#F59E0B",
      dotStyle: "rounded",
      eyeStyle: "dot",
      showWatermark: false,
    },
  },
  {
    id: "review-cream-a6",
    name: "Отзывы — крем",
    description: "A6 лежачий, тёплый бежевый фон, editorial-макет",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру на QR",
      labels: ["ОТЗЫВ", "БЫСТРО"],
      formatId: "a6l",
      layoutId: "editorial",
      paletteId: "cream",
      brandColor: "#A87C4F",
      dotStyle: "rounded",
      eyeStyle: "leaf",
      showWatermark: false,
    },
  },
  {
    id: "review-ocean-5x5",
    name: "Стикер 5×5 — Океан",
    description: "Квадратный стикер 5×5 см, синий градиент, стандарт",
    config: {
      headline: "ОЦЕНКА",
      ctaText: "Наведите камеру",
      labels: ["ОТЗЫВ"],
      formatId: "5x5",
      layoutId: "standard",
      paletteId: "ocean",
      brandColor: "#0E7490",
      dotStyle: "dots",
      eyeStyle: "circle",
      showWatermark: false,
    },
  },
  {
    id: "review-mint-5x5",
    name: "Стикер 5×5 — Мята",
    description: "Квадратный стикер 5×5 см, зелёный, минимализм",
    config: {
      headline: "ОТЗЫВ",
      ctaText: "Наведите камеру",
      labels: [],
      formatId: "5x5",
      layoutId: "standard",
      paletteId: "mint",
      brandColor: "#2F6B55",
      dotStyle: "rounded",
      eyeStyle: "rounded",
      showWatermark: false,
    },
  },
  {
    id: "review-bauhaus-7x7",
    name: "Стикер 7×7 — Геометрия",
    description: "Квадратный стикер 7×7 см, лаконичный макет",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру",
      labels: ["★★★★★"],
      formatId: "7x7",
      layoutId: "standard",
      paletteId: "light",
      brandColor: "#4F46E5",
      dotStyle: "squares",
      eyeStyle: "square",
      showWatermark: false,
    },
  },
  {
    id: "review-rose-a6",
    name: "Отзывы — Роза",
    description: "A6 лежачий, розовый градиент, стандартный макет",
    config: {
      headline: "ОЦЕНИТЕ НАС",
      ctaText: "Наведите камеру на QR",
      labels: ["ОТЗЫВ", "★★★★★"],
      formatId: "a6l",
      layoutId: "standard",
      paletteId: "rose",
      brandColor: "#BE185D",
      dotStyle: "dots",
      eyeStyle: "circle",
      showWatermark: false,
    },
  },
];
