-- AlterTable
ALTER TABLE "QRMenu" ADD COLUMN "askPhone"   BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "QRMenu" ADD COLUMN "askEmail"   BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "QRMenu" ADD COLUMN "askAddress" BOOLEAN NOT NULL DEFAULT false;
